version: "3.9"

services:
  docai:
    image: docai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_ENDPOINT=https://devocrback.victoriousdune-c6195d85.australiaeast.azurecontainerapps.io