version: "3.9"

services:

  sample:
    container_name: docai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - REACT_APP_ENDPOINT=http://localhost:5001