on: push

env:
  DEV_APP_RESOURCE_GROUP_NAME: "development-ocr"
  DEV_APP_RESOURCE_NAME: "devocrfront"
  IMAGE_REGISTRY_HOSTNAME: "devocrregistry.azurecr.io"
  IMAGE_NAME: "frontend"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output-build: ${{steps.id.outputs.build}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        id: id
        run: |
          BUILD=$(git rev-parse --abbrev-ref HEAD) && BUILD=${BUILD//\//-}
          docker build -t $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:latest -t $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$BUILD .
          docker login -u ${{secrets.DEV_ARM_CLIENT_ID}} -p ${{secrets.DEV_ARM_CLIENT_SECRET}} $IMAGE_REGISTRY_HOSTNAME
          docker push $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:latest
          docker push $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$BUILD
          echo "build=$BUILD" >> $GITHUB_OUTPUT
  
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: |
          az extension add -n containerapp
          az login --service-principal --username ${{secrets.DEV_ARM_CLIENT_ID}} --password ${{secrets.DEV_ARM_CLIENT_SECRET}} --tenant ${{secrets.DEV_ARM_TENANT_ID}}
          az account set --subscription ${{secrets.DEV_ARM_SUBSCRIPTION_ID}}
          az containerapp update -n $DEV_APP_RESOURCE_NAME -g $DEV_APP_RESOURCE_GROUP_NAME -i $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:${{needs.build.outputs.output-build}} --set-env-vars version="${{needs.build.outputs.output-build}}:run-$GITHUB_RUN_NUMBER"