on: push

env:
  APP_RESOURCE_GROUP_NAME: "development-ocr"
  APP_RESOURCE_NAME: "devocrfront"
  IMAGE_REGISTRY_HOSTNAME: "devocrregistry.azurecr.io"
  IMAGE_NAME: "docai"
  IMAGE_TAG: "latest"
  API: "https://devocrback.victoriousdune-c6195d85.australiaeast.azurecontainerapps.io"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: build
        run: |
          docker build --build-arg API=$API -t $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG -t $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_SHA .
          docker login -u ${{secrets.ARM_CLIENT_ID}} -p ${{secrets.ARM_CLIENT_SECRET}} $IMAGE_REGISTRY_HOSTNAME
          docker push $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_SHA
  
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli
    needs: build
    steps:
      - name: deploy
        run: |
          az extension add -n containerapp
          az login --service-principal --username ${{secrets.ARM_CLIENT_ID}} --password ${{secrets.ARM_CLIENT_SECRET}} --tenant ${{secrets.ARM_TENANT_ID}}
          az account set --subscription ${{secrets.ARM_SUBSCRIPTION_ID}}
          az containerapp update -n $APP_RESOURCE_NAME -g $APP_RESOURCE_GROUP_NAME -i $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_SHA