name: production

on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        default: 'uat'
        type: choice
        options:
        - uat
        - production

env:
  APP_RESOURCE_GROUP_NAME: "development-ocr"
  APP_RESOURCE_NAME: "devocrfront"
  IMAGE_REGISTRY_HOSTNAME: "devocrregistry.azurecr.io"
  IMAGE_NAME: "docai"
  IMAGE_TAG: "latest" 

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: job summary
        run: |
          echo "- logLevel: ${{ inputs.logLevel }}" >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: print-inputs
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: uat
        if: ${{ inputs.logLevel == 'uat'}}
        run: |
          echo 'uat'
          git status
          build=$(git rev-parse --abbrev-ref HEAD) && build=${build//\//-}
          echo $build
          # az extension add -n containerapp
          # az login --service-principal --username ${{secrets.ARM_CLIENT_ID}} --password ${{secrets.ARM_CLIENT_SECRET}} --tenant ${{secrets.ARM_TENANT_ID}}
          # az account set --subscription ${{secrets.ARM_SUBSCRIPTION_ID}}
      - name: production
        if: ${{ inputs.logLevel == 'production'}}
        run: |
          echo 'prod'
          git status
          build=$(git rev-parse --abbrev-ref HEAD) && build=${build//\//-}
          echo $build
          # az extension add -n containerapp
          # az login --service-principal --username ${{secrets.ARM_CLIENT_ID}} --password ${{secrets.ARM_CLIENT_SECRET}} --tenant ${{secrets.ARM_TENANT_ID}}
          # az account set --subscription ${{secrets.ARM_SUBSCRIPTION_ID}}
          # az containerapp update -n $APP_RESOURCE_NAME -g $APP_RESOURCE_GROUP_NAME -i $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_SHA